### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by MauricioRobayo**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Nicely done 👍
You did a great work building this project. but its not ready yet. Microverse guideline require some changes before we merging this to master. They are:

- [x] Your search input must have focus effect enabled. 

- [x] Because of the simplicity of this input tag, there is no need for the form tag.

- [x] Great work using images to define the 3 main sentences. But Microverse guidelines require that these sentences must be loaded using div tags instead. There is no need for the img tag here. Use the background of the div tag to load each sentence. Use 3 anchor tags for each sentence and inside each anchor tag, place the div tag and load the image using the background in the CSS file.

- [x] Microverse guidelines require that the 4 promo image are part of the footer. The footer is divided in 2 parts(top and bottom). The 4 promo images must be the top part of the footer.

- [x] You have to use the same approach of the 3 main sentences for the 4 promo images. Each one will be a div tag(loaded using its background), and each one will be inside its own anchor tag.

- [x] The bottom part should include links like copyright, terms of use, and privacy policy 

- [x] Its best practice to use the main tag for the most important content of your page. Kindly create a main tag and place your article tag inside it.

kindly make these changes and submit for code review again. Happy coding mate.

**Comment by MauricioRobayo** [comment]
@Torres-ssf Thank you for the detailed feedback, much appreciated!

**Review by mosaaleb — APPROVED** [review]
### Excellent work @archemiro :clap:

The UI is very clean, your code is organized. All requirements are handled.

Well done. You can now merge into master :+1:

Good luck with the next projects. Happy coding :computer:

**Comment by MauricioRobayo** [comment]
Thanks, @mosaaleb 😄 .

**Pull request merged**
